# Generated by Django 4.2.1 on 2023-05-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
