# Generated by Django 4.2.1 on 2023-05-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstat', '0004_alter_chat_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='messages',
            name='stiker',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
