# Generated by Django 4.2.1 on 2023-05-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstat', '0005_alter_messages_file_alter_messages_stiker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name_chat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
