# Generated by Django 4.2.1 on 2023-05-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstat', '0007_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_load',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webstat.chat'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='from_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webstat.user'),
        ),
        migrations.AlterField(
            model_name='users',
            name='chat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='from_id',
            field=models.IntegerField(null=True),
        ),
    ]
