# Generated by Django 4.2.1 on 2023-05-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstat', '0008_alter_chat_date_load_alter_messages_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='from_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webstat.users'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
