# Generated by Django 4.2.1 on 2023-05-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstat', '0009_alter_messages_from_id_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
