from django.db import models

class User(models.Model):
    user_id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=100)

class Message(models.Model):
    id = models.IntegerField(primary_key=True)
    edited = models.CharField(max_length=10)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)
    text_entities = models.JSONField()
    performer = models.CharField(max_length=100)
    thumbnail = models.CharField(max_length=100)
    date = models.CharField(max_length=100)
    mime_type = models.CharField(max_length=100)
    file = models.CharField(max_length=100)
    text = models.TextField()
    via_bot = models.CharField(max_length=100)
    date_unixtime = models.CharField(max_length=100)
    reply_to_message_id = models.IntegerField()
    photo = models.CharField(max_length=100)
    sticker_emoji = models.CharField(max_length=100)
    duration_seconds = models.IntegerField()
    members = models.JSONField()
    action = models.CharField(max_length=100)
    width = models.IntegerField()
    actor = models.CharField(max_length=100)
    media_type = models.CharField(max_length=100)
    height = models.IntegerField()
    edited_unixtime = models.CharField(max_length=100)
    from_id = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    forwarded_from = models.CharField(max_length=100)
    actor_id = models.CharField(max_length=100)
    saved_from = models.CharField(max_length=100)
